# Generated by Django 5.2.15 on 2026-06-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='image',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='documents/default.jpg', upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('docx', 'Word Document'), ('xlsx', 'Excel Spreadsheet'), ('csv', 'CSV File')], default='image', max_length=10),
        ),
    ]
